import type { JSONSchema } from "../dsl.js";

export function generateAjvModule(schema: JSONSchema, exportName = "validateAll"): string {
  return `// AUTO-GENERATED by schema-translator
// GEN-V3
// @ts-nocheck
import Ajv from "ajv/dist/2020.js";
import addFormats from "ajv-formats";

const schema = ${JSON.stringify(schema, null, 2)} as const;

const ajv = new Ajv({ allErrors: true, allowUnionTypes: true, useDefaults: true });
addFormats(ajv);

export const ${exportName} = ajv.compile(schema);
`;
}
