import type { JSONSchema } from "../dsl.js";

// Mapeo mínimo: para demo; en producción usar zod-to-json-schema o generadores más completos.
function jsonTypeToZod(node: any): string {
  if (node.$ref) {
    const name = String(node.$ref).split("/").pop();
    return name ? name + "Schema" : "z.any()";
  }
  if (node.enum) return `z.enum([${node.enum.map((e: any) => JSON.stringify(e)).join(", ")}])`;
  switch (node.type) {
    case "string":
      if (node.format === "email") return "z.string().email()";
      if (node.format === "uuid") return "z.string().uuid()";
      if (node.format === "date") return "z.string().date()";
      if (node.format === "date-time") return "z.string().datetime()";
      if (node.format === "uri") return "z.string().url()";
      return "z.string()";
    case "integer": return "z.number().int()";
    case "number":  return "z.number()";
    case "boolean": return "z.boolean()";
    case "array": {
      const items = jsonTypeToZod(node.items || {});
      let z = `z.array(${items})`;
      if (node.minItems !== undefined) z += `.min(${node.minItems})`;
      if (node.maxItems !== undefined) z += `.max(${node.maxItems})`;
      return z;
    }
    case "object":
      // handled elsewhere
      return "z.object({})";
    default:
      return "z.any()";
  }
}

export function generateZodModule(schema: JSONSchema): string {
  const defs = schema.definitions || {};
  const defBlocks: string[] = [];
  for (const [name, def] of Object.entries<any>(defs)) {
    const props = def.properties || {};
    const req = new Set<string>(def.required || []);
    const entries = Object.entries(props).map(([k, v]: any) => {
      let z = jsonTypeToZod(v);
      if (!req.has(k)) z += ".optional()";
      return `  ${JSON.stringify(k)}: ${z}`;
    });
    defBlocks.push(`export const ${name}Schema = z.object({\n${entries.join(",\n")}\n})${def.additionalProperties === false ? "" : ".passthrough()"};`);
  }

  const root = `export const RootSchema = z.object({\n${Object.keys(defs).map(n => `  ${JSON.stringify(n)}: ${n}Schema`).join(",\n")}\n}).strict();`;

  return `// AUTO-GENERATED by schema-translator
import { z } from "zod";

${defBlocks.join("\n\n")}

${root}
export type Root = z.infer<typeof RootSchema>;
`;
}
